config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "backend.minikube.local/guestbook"
image:
  repository: dimalegeza/helm-frontend
  tag: "1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: frontend.minikube.local
